-- MySQL Script generated by MySQL Workbench
-- 07/08/16 13:08:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema betsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema betsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `betsdb` DEFAULT CHARACTER SET utf8 ;
USE `betsdb` ;

-- -----------------------------------------------------
-- Table `betsdb`.`Bookmakers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`Bookmakers` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` CHAR(150) NULL DEFAULT NULL,
  `Hostname` CHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name` (`Name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`Sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`Sports` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` CHAR(250) NOT NULL,
  `Bookmaker` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_index` (`Name` ASC, `Bookmaker` ASC),
  INDEX `sportnames_fk0` (`Bookmaker` ASC),
  CONSTRAINT `sportnames_fk0`
    FOREIGN KEY (`Bookmaker`)
    REFERENCES `betsdb`.`Bookmakers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`Leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`Leagues` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` CHAR(250) NOT NULL,
  `Sport` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_index` (`Name` ASC),
  INDEX `leaguesnames_fk2_idx` (`Sport` ASC),
  CONSTRAINT `Sport_fk`
    FOREIGN KEY (`Sport`)
    REFERENCES `betsdb`.`Sports` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`Participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`Participants` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` CHAR(250) NOT NULL,
  `League` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_index` (`Name` ASC),
  INDEX `League_fk_idx` (`League` ASC),
  CONSTRAINT `League_fk`
    FOREIGN KEY (`League`)
    REFERENCES `betsdb`.`Leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`Handicaps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`Handicaps` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FirstForward` DOUBLE NOT NULL,
  `FirstWin` DOUBLE NOT NULL,
  `SecondForward` DOUBLE NOT NULL,
  `SecondWin` DOUBLE NOT NULL,
  `OddsDate` DATETIME NOT NULL,
  `Live` TINYINT(1) NOT NULL,
  `Href` CHAR(200) NULL DEFAULT NULL,
  `Actual` TINYINT(1) NOT NULL,
  `FirstParticipant` BIGINT(20) NOT NULL,
  `SecondParticipant` BIGINT(20) NOT NULL,
  `Bookmaker` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FirstParticipant_fk_idx` (`FirstParticipant` ASC),
  INDEX `SecondParticipant_fk_idx` (`SecondParticipant` ASC),
  INDEX `Bookmaker_fk_idx` (`Bookmaker` ASC),
  CONSTRAINT `FirstParticipant_fk`
    FOREIGN KEY (`FirstParticipant`)
    REFERENCES `betsdb`.`Participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SecondParticipant_fk`
    FOREIGN KEY (`SecondParticipant`)
    REFERENCES `betsdb`.`Participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Bookmaker_fk`
    FOREIGN KEY (`Bookmaker`)
    REFERENCES `betsdb`.`Bookmakers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`LeaguesMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`LeaguesMatch` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `League` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `League_fk_idx` (`League` ASC),
  UNIQUE INDEX `Unique` (`id` ASC),
  CONSTRAINT `League_fk`
    FOREIGN KEY (`League`)
    REFERENCES `betsdb`.`Leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`ParticipantsMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`ParticipantsMatch` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Participant` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_index` (`Participant` ASC),
  CONSTRAINT `fk_ParticipantsMatch_Participants1`
    FOREIGN KEY (`Participant`)
    REFERENCES `betsdb`.`Participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`SportsMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`SportsMatch` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Sport` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `MATCH` (`id` ASC),
  INDEX `Sport_fk_idx` (`Sport` ASC),
  CONSTRAINT `Sport_fk`
    FOREIGN KEY (`Sport`)
    REFERENCES `betsdb`.`Sports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `betsdb`.`MoneyLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betsdb`.`MoneyLine` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FirstWin` DOUBLE NOT NULL,
  `SecondWin` DOUBLE NOT NULL,
  `Draw` DOUBLE NULL,
  `OddsDate` DATETIME NOT NULL,
  `GameDate` DATETIME NOT NULL,
  `Live` BINARY(1) NOT NULL,
  `LiveDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
